development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: mongo_salesdemo_development

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch(ENV.fetch("REDIS_PROVIDER", "REDIS_URL")) { "redis://localhost:6379/1" } %>
  channel_prefix: mongo_salesdemo_production
